-- AlterTable
ALTER TABLE "Product" ADD COLUMN "moisturePct" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "ashPct" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "taurinePct" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "chondroitinMgPerKg" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "glucosamineMgPerKg" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "ingredients" TEXT;
